USE [master]
GO

/****** Object:  Database [UnimedBosch]    Script Date: 06/02/2023 14:17:31 ******/
CREATE DATABASE [UnimedBosch]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UnimedBosch', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\UnimedBosch.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UnimedBosch_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\UnimedBosch_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UnimedBosch].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UnimedBosch] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UnimedBosch] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UnimedBosch] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UnimedBosch] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UnimedBosch] SET ARITHABORT OFF 
GO

ALTER DATABASE [UnimedBosch] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UnimedBosch] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UnimedBosch] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UnimedBosch] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UnimedBosch] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UnimedBosch] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UnimedBosch] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UnimedBosch] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UnimedBosch] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UnimedBosch] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UnimedBosch] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UnimedBosch] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UnimedBosch] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UnimedBosch] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UnimedBosch] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UnimedBosch] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UnimedBosch] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UnimedBosch] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UnimedBosch] SET  MULTI_USER 
GO

ALTER DATABASE [UnimedBosch] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UnimedBosch] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UnimedBosch] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UnimedBosch] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UnimedBosch] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UnimedBosch] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [UnimedBosch] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UnimedBosch] SET  READ_WRITE 
GO

